<?php
return [
    'cancel' => 'Annulla',
    'continue' => 'Continua',
    'back' => 'Indietro',
    'load' => 'Carica',
    'change' => 'Cambia',
    'edit' => 'Modifica',
    'insert' => 'Inserisci',
    'assign' => 'Assegna',
    'delete' => 'Elimina',
    'save' => 'Salva',
    'add' => 'Aggiungi',
    'filter' => 'Filtra',
    'disable' => 'Disabilita',
    'enable' => 'Abilita',
    'save-and-close' => 'Salva e chiudi',
    'accept' => 'Accetta',
    'refuse' => 'Rifiuta non necessari',
    'customize' => 'Personalizza',

    'active' => 'Attivo',
    'inactive' => 'Inattivo',
    'disactivated' => 'Disattivato',
    'enabled' => 'Abilitato',
    'disabled' => 'Disabilitato',
    'create' => 'Crea',
    
    'select' => 'Seleziona',
    'open' => 'Apri',
    'close' => 'Chiudi',
    'confirm' => 'Conferma',
    'are-you-sure' => 'Sei sicuro di voler cancellare questo elemento?',
    'confirm-cancelation' => 'Conferma cancellazione',
];